/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.*;
import java.nio.file.*;
import java.util.*;


public class App
{


    public static void main(String[] args)
    {
        Path testFile = Paths.get("src/main/resources/gates.js");

        System.out.println(checkJavaScriptFile(testFile));
    }

    public static String checkJavaScriptFile(Path filePath){

        Scanner fileScanner;
        String message = "Current errors:  \n";
        try{

            fileScanner = new Scanner(new File(filePath.toUri()));
            int currentLineNumber = 1;

            while( fileScanner.hasNextLine()){
                String currentLine = fileScanner.nextLine();
                if(!currentLine.endsWith(";") && !currentLine.endsWith("}") && !currentLine.endsWith("{") && !currentLine.contains("if") && !currentLine.contains("else") && !currentLine.isEmpty() && !currentLine.startsWith("//") ) {
                    message += "Line "+ currentLineNumber +": Missing semicolon.\n";
                }
                currentLineNumber ++;
            }

        }catch (FileNotFoundException e)
        {
            e.printStackTrace();
        }

        return message;
    }
}