package basiclibrary;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.util.*;

import basiclibrary.Library;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testRollLength(){
        int[] roller = Library.roll(7);
        assertTrue(roller.length == 7);
    }

    @Test public void testRollRange(){
        int[] roller = Library.roll(7);

        for (int i = 0; i < 7; i++){
            assertTrue(roller[i] > 0 && roller[i] <= 6);
        }
    }

   @Test public void testDuplicates(){
        int[] arrayOne = {1, 2, 3, 4, 4, 5, 6, 7};
        int[] arrayTwo = {1, 2, 3, 4, 5, 6, 7, 8};

        assertEquals(true, Library.containsDuplicates(arrayOne));
        assertEquals(false, Library.containsDuplicates(arrayTwo));
   }

  @Test public void testAverage(){
        int[] test= {1, 2, 3, 4, 5};
        assertEquals(3, Library.average(test));
  }

  @Test public void testMultiDimensional(){
      int[][] weeklyMonthTemperatures = {
              {66, 64, 58, 65, 71, 57, 60},
              {57, 65, 65, 70, 72, 65, 51},
              {55, 54, 60, 53, 59, 57, 61},
              {65, 56, 55, 52, 55, 62, 57}
      };

      int[] returnArray = {55, 54, 60, 53, 59, 57, 61};
      assertArrayEquals(returnArray, Library.arrayOfArrays(weeklyMonthTemperatures));
  }
}
