/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static int[] roll(int numOfRolls){
        int max = 6;
        int min = 1;
        int range = max - min + 1;

        int returnArray[] = new int[numOfRolls];

        for (int i = 0; i < numOfRolls; i++){
            returnArray[i] = (int)(Math.random() * range) + min;
        }
        return returnArray;
    }

    public static boolean containsDuplicates(int[] array){
        for (int i = 0; i < array.length; i++){
            for (int j = i + 1 ; j < array.length; j++){
                if (array[i] == array[j]) {
                    return true;
                }
            }
        }
        return false;
    }

    public static float average(int[] array){
        float accumulator = 0;
        for(int value : array){
            accumulator += value;
        }
        return  (float)accumulator / array.length;
    }

    public static int[] arrayOfArrays(int[][] arrays){
        int average[] = new int[arrays.length];
        int total[] = new int[arrays[0].length];
        int sum = 0;
        int determinant = 0;
        for (int i = 0; i < arrays.length; i++){
            for (int j = 0; j < arrays[0].length; j++){
                total[i] = sum + arrays[i][j];
            }
            average[i] = total[i] / arrays.length;
        }
        for (int x = 0; x < average.length; x++){
            for (int y = x + 1; y < average.length; y++){
                if (average[x] > average[y]){
                    determinant = x;
                }
            }
        }
        return arrays[determinant];
    }

    public static String weatherAnalysis(int[][] month){
        HashSet<Integer> tempSet = new HashSet<>();

        int minTemp = 200;
        int maxTemp = -200;
        String response = "";

        for (int[] week : month){
            for (int day : week) {
                if (day > maxTemp) {
                    maxTemp = day;
                }else if (day < minTemp){
                    minTemp = day;
                }
                if(!tempSet.contains(day)){
                    tempSet.add(day);
                }
            }
        }

        response += ("High: " + maxTemp + "\n");
        response += ("Low: " + minTemp + "\n");

        for (int i = minTemp; i <= maxTemp; i++) {
            if (!tempSet.contains(i)) {
                response += ("Never saw temperature: " + i + "\n");
            }
        }
        return response;
    }

    public static String tally(ArrayList<String> votes){
        HashMap<String, Integer> ballot = new HashMap<>();
        String winner = "";
        int highestVoteCount = 0;

        for(String contender : votes){
            if(!ballot.containsKey(contender)){
                ballot.put(contender, 1);
            }else{
                ballot.put(contender, ballot.get(contender) + 1);
            }
        }
        for(String contender : ballot.keySet()){
            if(ballot.get(contender) > highestVoteCount){
                highestVoteCount = ballot.get(contender);
                winner = contender;

            }
        }
        return winner + " received the most votes!";
    }


}
